/**
 * @file    config.h
 * @brief   GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 *
 * EROS static application configuration (OSEK "OIL" equivalent).
 * Edit app.yaml and regenerate; see tools/erosgen.py.
 */

#ifndef EROS_CONFIG_H
#define EROS_CONFIG_H

#include "eros_types.h"

/* ---- system counter --------------------------------------------- */
#define OS_TICK_HZ            1000u
#define OS_TICK_MS            1u
#define OS_ALARM_MAX_OFFSET   32767u

/* ---- tasks: TaskID == priority == ready-mask bit ----------------- */
/* WCET budgets (ticks, monitored at +/-1 tick):                      */
/*   TASK_INIT       prio 0  wcet <= 1 tick(s)  (autostart, one-shot) */
/*   TASK_BLINK      prio 1  wcet <= 1 tick(s)  (100 ms) */
#define OS_NUM_TASKS          2u

#define TASK_INIT             ((TaskType)0u)
#define TASK_BLINK            ((TaskType)1u)

extern void Task_Init(void);
extern void Task_Blink(void);

/* ---- alarms: one cyclic alarm per periodic task ------------------ */
#define OS_NUM_ALARMS         1u

#define ALARM_BLINK           ((AlarmType)0u) /* 100 ms -> TASK_BLINK */

/* Period macros for SetRelAlarm/SetAbsAlarm calls in the app. */
#define TASK_BLINK_PERIOD_TICKS 100u

/* ---- resources (IPCP; ceiling = highest-priority user) ---------- */
#define OS_NUM_RESOURCES      1u

#define RES_IO                ((ResourceType)0u) /* users: BLINK */

/* ---- fixed-block pool -------------------------------------------- */
#define OS_POOL_BLOCK_SIZE    8u
#define OS_POOL_NUM_BLOCKS    4u

/* ---- watchdog aliveness ------------------------------------------ */
#define OS_ALIVE_REQUIRED_MASK \
    ((uint8_t)((1u << TASK_BLINK)))

/* ---- hooks -------------------------------------------------------- */
#define OS_CFG_STARTUPHOOK    1
#define OS_CFG_ERRORHOOK      1
#define OS_CFG_SHUTDOWNHOOK   1

/* ---- stack monitoring --------------------------------------------- */
#define OS_STACK_CANARY        0xC5u
#define OS_STACK_GUARD_BYTES   8u
#define OS_STACK_PAINT_MARGIN  16u

/* ---- compile-time validation -------------------------------------- */
OS_STATIC_ASSERT(OS_NUM_TASKS >= 1u, "at least one task required");
OS_STATIC_ASSERT(OS_NUM_TASKS <= 8u, "ready queue is an 8-bit mask: max 8 tasks");

OS_STATIC_ASSERT(
    ((1u << TASK_INIT) | (1u << TASK_BLINK)) ==
    ((1u << OS_NUM_TASKS) - 1u),
    "task IDs/priorities must be unique bit positions 0..OS_NUM_TASKS-1");

OS_STATIC_ASSERT(OS_NUM_ALARMS >= 1u, "at least one alarm required");
OS_STATIC_ASSERT((ALARM_BLINK < OS_NUM_ALARMS),
                 "alarm ID out of range");

OS_STATIC_ASSERT(OS_NUM_RESOURCES <= 8u, "resource held-mask is 8-bit");
OS_STATIC_ASSERT((RES_IO < OS_NUM_RESOURCES),
                 "resource ID out of range");

OS_STATIC_ASSERT((OS_POOL_NUM_BLOCKS >= 1u) && (OS_POOL_NUM_BLOCKS <= 8u),
                 "pool allocation bitmask is 8-bit: 1..8 blocks");
OS_STATIC_ASSERT(OS_POOL_BLOCK_SIZE >= 1u,
                 "free-list link needs one byte per block");

OS_STATIC_ASSERT((OS_ALIVE_REQUIRED_MASK & ~((1u << OS_NUM_TASKS) - 1u)) == 0u,
                 "aliveness mask references a non-existent task");

#endif /* EROS_CONFIG_H */
