/**
 * @file    os_gen.h
 * @brief   GENERATED by tools/erosgen.py from app.yaml - DO NOT EDIT
 *
 * Regenerated on every erosgen run - never edit. Include it
 * from main.c and call Board_ConfigurePins() in StartupHook()
 * and OS_StartAlarms() in the autostart task, so pin and alarm
 * wiring stay in sync with the YAML.
 */

#ifndef OS_GEN_H
#define OS_GEN_H

#include <avr/io.h>
#include "eros.h"

/** Pin directions/pull-ups + enabled-driver init. Call from
 *  StartupHook() (interrupts still disabled). */
static inline void Board_ConfigurePins(void)
{
    DDRL |= (uint8_t)(1u << PL7);  /* LED output */
    PORTL &= (uint8_t)~(1u << PL7);
    DDRB |= (uint8_t)(1u << PB7);  /* HEARTBEAT output */
    PORTB &= (uint8_t)~(1u << PB7);
}

/** Arm every cyclic alarm with ALIGNED releases (all first
 *  expiries at the base period so shared release points
 *  coincide). Call from the autostart task. */
static inline void OS_StartAlarms(void)
{
    (void)SetRelAlarm(ALARM_BLINK, 100u, TASK_BLINK_PERIOD_TICKS);
}

#endif /* OS_GEN_H */
